# Your workflow name.
name: CI/CD for Dockerized Flask App.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Login to DockerHub. # Your custom step name
        uses: docker/login-action@v2 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Heroku app.

          # The email address associated with your Heroku account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          username: ${{ secrets.DOCKER_USERNAME }}
          
          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          # Name of the heroku application to which the build is to be sent.
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/flask-app:latest3

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          

          # (Optional, default: "")
          # Additional options of docker build command.
        

          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          # For more information look at https://devcenter.heroku.com/articles/process-model
          
          
   
          
### ⬆ IMPORTANT PART ⬆ ###
